config/routes.rb
Rails.application.routes.draw do

root 'welcome#index'
  resources :categories, only: [:show]
  resources :classifieds, only: [:new, :create, :index, :show]

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :clasifieds 
end

app/models/classified.rb
class Classified < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController

  def index
    @classifieds = Classified.all
  end


  def new
    @classified = Classified.new
    @classified.build_category
  end

  def create
    @classified = Classified.new(safe_classified_params)
    @classified.build_category(safe_category_params)

    if @classified.save
      redirect_to classifieds_path
    else
      render 'new'
    end
  end

  private
  def safe_classified_params
    params.require(:classified).permit(:title, :price, :description)
  end

  def safe_category_params
    params.require(:category).permit(:name)
  end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/classifieds/index.html.erb
<h1>Classifieds</h1>
<section>
  <% @classifieds.each do |classifieds|  %>
    <article>
        <h2> <%= classifieds.title %> </h2>
        <p> <%= classifieds.description %> </p>

        <div> <%= "$#{classifieds.price}" %> </div>
        <div> <%= classifieds.category.name %> </div>
    </article>
  <% end %>
</section>

app/views/classifieds/new.html.erb
<h1> Create a Classified </h1>

<%= form_for @classified do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= fields_for @classified.category do |category_form| %>
    <%= category_form.label :name %>
    <%= category_form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: "form-control" %>
  </div>
  <%= form.submit "Create Classified" %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StuffFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

<%= link_to "Create new classified", new_classified_path%>
<%= link_to "View list of classifieds", classifieds_path %>